### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by masagermany** [gmansillo/simple#14] opened 2016-05-25 11:11 UTC
I created a menu " Category list - Display a list of documents in a category ". A click on this menu entry leads to this:

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1 LIMIT 0, 100' at line 6 SQL=SELECT DISTINCT a.*,uc.name AS editor FROMabc_simplefilemanagerAS a LEFT JOIN abc_users AS uc ON uc.id=a.checked_out LEFT JOIN abc_users AS created_by ON created_by.id = a.created_by WHERE a.catid = 25 ORDER BY a.file_created 1 LIMIT 0, 100`

**Comment by gmansillo** [comment] 2016-05-25 13:37
Hello masagermany,
i'm not able to reproduce the issue. What's the history of you Simple File Manager installation? Is it a new installation or did you update it from previous versions?

**Comment by xxkiefxx** [comment] 2016-05-29 13:54
To replicate the error you can try to enter in the menu option (in my case it's category list) and set the show icons on HIDE.

**Comment by gmansillo** [comment] 2016-05-30 08:39
Gotcha!
It'll be fixed with the next update.

**Closed as completed** 2016-06-06 13:51 UTC
Labels: bug
