### ISSUE TITLE
documents don't work on backend

### ISSUE THREAD

**Issue by Jose-Alberto-Fernandez** [gmansillo/simple#107] opened 2018-10-17 09:12 UTC
Hi, thanks for your great work.
I can create categories in firedrive component, but when I try to create a section documents from backend this goes to error 500 `https://XXXX.com/administrator/index.php?option=com_firedrive`

`Fatal error: Class 'FiredriveHelper' not found in /home/transcri/public_html/administrator/components/com_firedrive/views/documents/view.html.php on line 74`

I have updated Joomla 3.8.13 and Firedrive component 5.2.3 but the component still don't work

**Comment by gmansillo** [comment] 2018-10-17 19:00
Hola @Jose-Alberto-Fernandez !
Thank you for your feedback. Please can you check if the file _administrator/components/com_firedrive/helpers/firedrive.php_ exists and that its line 20 is like the following one?
`class FiredriveHelper extends JHelperContent`

**Comment by gmansillo** [comment] 2018-10-17 19:04
Another test that you can do is to paste the following code at line 10 of the same file (_administrator/components/com_firedrive/helpers/firedrive.php_ )
`JLoader::register('FiredriveHelper', JPATH_ADMINISTRATOR . '/components/com_firedrive/helpers/firedrive.php');`

Does one of the proposed solutions solve the issue?

**Comment by Jose-Alberto-Fernandez** [comment] 2018-10-17 22:05
Hi Giovani, thank's for promptly responding
The first solution already exists on line 15 in file _firedrive.php_ 
The second proposal solution don't solve the problem.

**Comment by gmansillo** [comment] 2018-10-17 22:20
I'm currently working with joomla 3.8.13 but i am not able to riproduce the issue since all seems to work perfectly with this version. Can you help me with other informations? Is it a fresh install or did you update firedrive from previous versions? Can you give me other useful informations?

**Comment by Jose-Alberto-Fernandez** [comment] 2018-10-17 22:46
This is a first installation since I have tried several times since three months with the Simple File Manager Component but it never worked. I uninstalled and wanted to try the latest Firedrive version but the problem persists.
Do you think my .htaccess file can cause problems?

**Comment by gmansillo** [comment] 2018-10-18 08:26
Wich php version?

**Comment by Jose-Alberto-Fernandez** [comment] 2018-10-18 08:34
Version Apache | 2.4.35 --- Version PHP | 5.6.30

**Comment by gmansillo** [comment] 2018-10-18 10:05
I've just installed all necessary stuff for creating a testing environment as similar as possible to your.
I'm still not able to reproducing the issue: 
![2018-10-18-120119_1366x768_scrot](https://user-images.githubusercontent.com/11967003/47147091-be70eb00-d2cd-11e8-8ceb-8127f9b3a1ef.png)

Can be a server problem?

**Comment by Jose-Alberto-Fernandez** [comment] 2018-10-18 11:23
I have tried all versions Php 5.6.38 - 7.0.32 - 7.1.22 - 7.2.10, now I have Php 7.2.10 but it does not work
![screenshot_20181018-131735](https://user-images.githubusercontent.com/43699931/47151058-ee71bb80-d2d8-11e8-86bc-930c0487401c.jpg)

**Comment by gmansillo** [comment] 2018-10-18 20:44
Unfortunately, as long as I can not reproduce the issue, i can't do anything for fixing it. It could be also a server or a Joomla! Issue (maybe an old update failure?). 

As final attempt you can try to replace the call to the missing class method with the class method content. In _administrator/components/com_firedrive/helpers/firedrive.php_ you should replace:
```
FiredriveHelper::addSubmenu('documents');
```
with:
```
JHtmlSidebar::addEntry(
	JText::_('COM_FIREDRIVE_SUBMENU_DOCUMENTS'), 'index.php?option=com_firedrive', $vName == 'documents'
);

JHtmlSidebar::addEntry(
	JText::_('COM_FIREDRIVE_SUBMENU_CATEGORIES'), 'index.php?option=com_categories&extension=com_firedrive', $vName == 'categories'
);
```
but it couldn't be a definitive fix. We need to investigate about what is causing the issue on your istance.

**Comment by Jose-Alberto-Fernandez** [comment] 2018-10-19 08:47
Unfortunately, that class method already exists in the file Firedrive.php
I will check my server and review the errors in my joomla.
Previously I installed Phoca and JDownloader but I want Firedrive because it has all the requirements I need for my website.

**Comment by gmansillo** [comment] 2018-10-19 10:25
Oops, I've just noticed that I specified the wrong file to edition my second message: you should paste this code:
```
JLoader::register('FiredriveHelper', JPATH_ADMINISTRATOR . '/components/com_firedrive/helpers/firedrive.php');
```
at line 10 of administrator/components/com_firedrive/views/documents/view.html.php and not in the previously specified file. Please try again this method because my previous suggestion was wrong!

In my last message i was suggesting you to replace in  administrator/components/com_firedrive/views/documents/view.html.php the line

```
FiredriveHelper::addSubmenu('documents');
```

with

```
JHtmlSidebar::addEntry(
	JText::_('COM_FIREDRIVE_SUBMENU_DOCUMENTS'), 'index.php?option=com_firedrive', $vName == 'documents'
);

JHtmlSidebar::addEntry(
	JText::_('COM_FIREDRIVE_SUBMENU_CATEGORIES'), 'index.php?option=com_categories&extension=com_firedrive', $vName == 'categories'
);
```
And not to redefine the method. In this way you don't need to call the "missing" class!

Please let me know!

**Comment by Jose-Alberto-Fernandez** [comment] 2018-10-19 10:57
Wow, you're great, it really worked adding the code in _administrator/components/com_firedrive/views/documents/view.html.php_

Now I'm going to introduce files and verify that everything really works correctly.

Thank you very much for solving this problem so quickly.

**Comment by gmansillo** [comment] 2018-10-19 11:07
You're welcome!
I'm going to close the issue and to add that line to the source code. You'll find the definitive fix in the next update.  Thank you for your patience!

In addition, if you want you can leave a short review of Firedrive at https://extensions.joomla.org/extension/firedrive/
In this way you will help Firedrive growing up. Please note that only rates of 100/100 means a good work!

Thank you,
Giovanni

**Closed as completed** 2018-10-20 17:07 UTC
